README.md

isuue #41 
close #41 
I've opened the pull request.
Please merge it after reviewing.

Updated README.md - removed grammatical errors

---

README.md

npm cmd update  

---

README.md

Added more badges as suggested other than the tech badges

Added badges README.md

---

public/index.html

- Added primary meta elements which plays a crucial role in terms of search engine optimization

[ADD]: PRIMARY META ELEMENTS, IMPROVES SEO 🚀

---

package-lock.json
package.json
src/components/ModelViewer/ErrorPage.js
src/index.js

Routing added

---

public/index.html
src/App.css
src/index.css

closed #84 
1. add description meta tag , and change website name from react app to AR-Webstore
2. align item to the center , remove App css code because its not working  .app classname is not defined 
and add some css in body tag

website name updated and item align center

---

CONTRIBUTING.md

Improvements to CONTRIBUTING.md issue#94

---

src/App.css
src/components/ModelViewer/ModelViewer.js

#64 
mljkl
- [ x] My code follows the code style of this project.
- [ x] All new and existing tests passed.

Product Card Improvement

---

.github/ISSUE_TEMPLATE/documentation.yml
.github/ISSUE_TEMPLATE/styles.yml

- **Created styles.yml and documentation.yml Files in GitHub Issue Templates Folder.**
- **After that, I have added Suitable Code Placed in Respective Files.**

fix: Added styles.yml and documentation.yml Files in GitHub ISSUE TEMPLATES

---

package-lock.json
src/App.js
src/components/Footer.css
src/components/Footer.js

Add footer 

---

.github/ISSUE_TEMPLATE/bug.yml
.github/ISSUE_TEMPLATE/documentation.yml
.github/ISSUE_TEMPLATE/styles.yml

- **Resolved Minor Bugs in bug.yml, documentation.yml and styles.yml File.**
- **Main Problem is of This Errors happened in Specific Files are having Indentation and Spacing related Problems.**
- **so, I can cross checked with Validator Tools and That Provide Valid YAML put into respective Files.**

fix: Validated YAML Errors in Multiple Files and Link Issue is Solved in bug.yml File

---

src/Products/ProductList.css
src/components/ModelViewer/ModelViewer.js

https://github.com/ShwetKhatri2001/AR-Webstore/assets/103810119/50c95428-a6aa-4f14-8cf7-ce3576f70edf

Resolve Footer and card is overlapping problem and card responsive ness

---

package-lock.json
src/App.js
src/components/About/About.css
src/components/About/About.js
src/components/Header/Header.js

fixed #171
Currently About Us page is directly redirecting GitHub page.
I added a separate About Us page with all the information given in the Git Hub.

Added : About page

---

src/App.css
src/components/ProductList/ProductList.css

#175 
[X] Centered the items in the product list
[X] full screen button on hover text was fixed

Centered the product list

---

security.txt

security.txt file added

---

src/components/Header/Header.js
src/components/Header/styles.css

Navbar UI FIXED

---

src/components/About/About.css
src/components/Header/Header.jsx
src/components/Header/styles.css

Animation added!
Kindly merge the PR or let me know for any further changes required to be made.

Added animation in About page.

---

src/components/Footer/Footer.js

Fix: about link

---

.vscode/settings.json
package-lock.json
package.json
src/App.css
src/components/ModelViewer/ModelViewer.js

I have resolved the previous issues kindly review it for issue number #212

All issues resolved

---

src/components/About/About.css
src/components/About/About.js

Fixes #204 
I have done all the changes as you said in the modified code. Kindly review them.

Set about page for all screen types

---

package-lock.json
package.json
src/components/ModelViewer/ModelViewer.js
src/components/ProductList/ProductList.js

I have implemented the lazy loading.

Lazy Loading implemented

---

src/components/Feedback/Feedback.css
src/components/Feedback/Feedback.js

Added the code for the new feedback page with SMTPJs Functionality
Closes #177 
Modified the code of FeedBack Page

Feed back page

---

src/components/About/About.css
src/components/About/About.js
src/components/About/ContributorSection.js
src/components/About/contributor.css

Closes #223 
Enhanced contributors' section by making the contributors list dynamic:
https://github.com/ShwetKhatri2001/AR-Webstore/assets/132138302/34660c79-cbe3-436f-b0d6-0ab768e2815d
Kindly merge this PR under SWOC label. Thankyou!

contributors section improved.

---

.dockerignore
README.md
dockerfile
package-lock.json

Fixes #218 
Added dockerfile, there will some change required in readme file such project can be run `docker run -p 3000:3000` ar-webstore

added docker functionality

---

package-lock.json
package.json
src/App.css
src/components/About/About.css
src/components/About/About.js
src/index.css

Scrollbutton changes

---

src/App.js
src/components/Header/Header.jsx
src/components/SignIn/SignIn.css
src/components/SignIn/Signin.js
src/components/SignUp/SignUp.css
src/components/SignUp/SignUp.js
src/index.js

**Fixes** #100 
**Changes:** Added Sign-in and Sign-up pages
Screenshots:
Please let me know if any changes are required

fix: Added sign-in and sign-up

---

src/App.css

updated the full screen and help button UI

---

package-lock.json
src/App.js
src/components/Header/Header.jsx
src/components/ModelViewer/ModelViewer.js
src/components/ProductList/ProductList.js
src/components/Wishlist/WishList.css
src/components/Wishlist/WishList.js
src/index.css

I have now successfully implemented wishlist section.
- [X ] All new and existing tests passed.
I am contributing under SWOC 2024.

WishList Implemented
